### ISSUE TITLE
Add flake8 tests as Github Action to lint code

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#318]

**Comment by brendancol** [comment]
@giancastro something like:

```yaml
    - name: Lint with flake8
      run: |
        # $CONDA/bin/conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        # $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
```
